# Generated by Django 4.1.3 on 2022-12-05 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primeraapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('tamanio', models.CharField(max_length=15)),
                ('ubicacion', models.CharField(max_length=15)),
                ('maxi_person', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=15)),
            ],
        ),
    ]
