# Generated by Django 4.1.3 on 2022-12-05 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('primeraapp', '0002_area'),
        ('evaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='primeraapp.area'),
        ),
    ]
